import './style'

export { default as Edit } from './icons/Edit'
export { default as Search } from './icons/Search'
export { default as Check } from './icons/Check'
export { default as Message } from './icons/Message'
export { default as Star } from './icons/Star'
export { default as Delete } from './icons/Delete'
export { default as View } from './icons/View'
export { default as StarFilled } from './icons/StarFilled'
export { default as Close } from './icons/Close'